name: Validação

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  testes:
    name: Testes automatizados
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Executar testes
        run: npm test
